# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(blank=True, max_length=3, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('time_sent', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=170, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('longitude', models.FloatField(default=-93.265)),
                ('latitude', models.FloatField(default=44.9778)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('role', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('partner', models.CharField(default='Wellstone Action', max_length=45)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_id', models.CharField(blank=True, max_length=3, null=True)),
                ('dateandtime', models.DateTimeField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=10, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
        migrations.AddField(
            model_name='message',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Training'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Series'),
        ),
    ]
